language: node_js
node_js:
  - "8"
sudo: false
cache: yarn
after_success: 'npm run coveralls && npm run docs'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: ./docs